import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  textbookSidebar: [
    {
      type: 'category',
      label: 'Week 1-2: Introduction to Physical AI',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'week-01-02-intro'},
      ],
    },
    {
      type: 'category',
      label: 'Week 3-5: ROS 2 Fundamentals',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'week-03-05-ros2'},
      ],
    },
    {
      type: 'category',
      label: 'Week 6-7: Digital Twin Simulation',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'week-06-07-digital-twin'},
      ],
    },
    {
      type: 'category',
      label: 'Week 8-10: NVIDIA Isaac Sim',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'week-08-10-isaac-sim'},
      ],
    },
    {
      type: 'category',
      label: 'Week 11-13: Vision-Language-Action',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'week-11-13-vla'},
      ],
    },
    {
      type: 'category',
      label: 'Week 13: Capstone Project',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'week-13-capstone'},
      ],
    },
  ],
};

export default sidebars;
